name: binaryoptions
favicon: null
layout_spectrum: 0.20388565119355917
typography_spectrum: 0.31802393426187336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.42625972419045866
  lightness: 0.1556374013889581
  saturation: 0.843354056822136
  rhythmicContrast: 0.12098398781381547
purpose: []
